### ISSUE TITLE
Bower package ?

### ISSUE THREAD

**Issue by armandchard** [padsbanger/angular-backtop#9]
Hello, 

Can you make it a bower package please ?
I like your directive but I even like to include it with bower package.

Thank you.

**Comment by padsbanger** [comment]
Hi, sure no problem. Shouldn`t be much work. I will do this when I catch some free time.

**Comment by padsbanger** [comment]
Bower package registered. 
Type `bower install --save angular-backtop` and the rest should be taken care by Bower.

Cheers

**Comment by armandchard** [comment]
Thanks a lot :)

**Comment by oliamb** [comment]
Hi,

Do you mind if I provide a pull request for a proper bower.json file?
It is considered a good practice to have bower use tagged version from your repository instead of master.

I know it is a bit more boilerplate as you then have to create git tag of your stable version, but I think it is worth it. 

Thanks for the plugin anyway, it is very useful!

**Comment by padsbanger** [comment]
@oliamb sure, go ahead :+1:
